[package]
name = "speed_tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.19"
gethostname = "0.4.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

